version: '3'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    container_name: ollama

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    container_name: redis-stack

volumes:
  ollama_data:
